"""Allowlisted data access layer.

Every query here is a fixed, parameterised statement. There is NO function that accepts SQL text,
and nothing generated by an LLM ever reaches the database. Student-scoped methods require the
student_id explicitly and always filter on it.
"""
from __future__ import annotations

import json
import sqlite3
from typing import Iterable, Optional

from app.core.clock import now_iso
from app.database.models import (
    AttendanceRow,
    ChunkRow,
    CourseRow,
    ResultRow,
    RuleRow,
    StudentRow,
)
from app.database.sqlite import get_conn


# --------------------------------------------------------------------------------------------
# Students (personal data: always scoped by student_id)
# --------------------------------------------------------------------------------------------
class StudentRepo:
    def get(self, student_id: str) -> Optional[StudentRow]:
        with get_conn() as c:
            row = c.execute(
                "SELECT student_id, full_name, programme, batch_year, current_semester, cgpa, active_backlogs "
                "FROM students WHERE student_id = ?",
                (student_id,),
            ).fetchone()
        return StudentRow(**dict(row)) if row else None

    def upsert(self, row: StudentRow, conn: Optional[sqlite3.Connection] = None) -> None:
        sql = (
            "INSERT INTO students(student_id, full_name, programme, batch_year, current_semester, cgpa, active_backlogs) "
            "VALUES (?,?,?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET "
            "full_name=excluded.full_name, programme=excluded.programme, batch_year=excluded.batch_year, "
            "current_semester=excluded.current_semester, cgpa=excluded.cgpa, active_backlogs=excluded.active_backlogs"
        )
        args = (row.student_id, row.full_name, row.programme, row.batch_year, row.current_semester, row.cgpa, row.active_backlogs)
        if conn is not None:
            conn.execute(sql, args)
        else:
            with get_conn() as c:
                c.execute(sql, args)

    def count(self) -> int:
        with get_conn() as c:
            return int(c.execute("SELECT COUNT(*) FROM students").fetchone()[0])

    def identity_lexicon(self) -> dict[str, set[str]]:
        """Names and ids used ONLY to detect references to other people in a question.

        The result is used for pattern matching inside the privacy checker and is never returned
        to a caller or written to logs.
        """
        with get_conn() as c:
            rows = c.execute("SELECT student_id, full_name FROM students").fetchall()
        names: set[str] = set()
        ids: set[str] = set()
        for r in rows:
            ids.add(r["student_id"].upper())
            full = r["full_name"].strip()
            names.add(full.lower())
            for part in full.split():
                if len(part) >= 3:
                    names.add(part.lower())
        return {"ids": ids, "names": names}


# --------------------------------------------------------------------------------------------
# Courses (public catalogue)
# --------------------------------------------------------------------------------------------
class CourseRepo:
    def get(self, course_code: str) -> Optional[CourseRow]:
        with get_conn() as c:
            row = c.execute(
                "SELECT course_code, course_name, programme, semester, credits FROM courses WHERE course_code = ?",
                (course_code.upper(),),
            ).fetchone()
        return CourseRow(**dict(row)) if row else None

    def list_for_programme(self, programme: Optional[str] = None) -> list[CourseRow]:
        with get_conn() as c:
            if programme:
                rows = c.execute(
                    "SELECT course_code, course_name, programme, semester, credits FROM courses "
                    "WHERE programme = ? ORDER BY semester, course_code",
                    (programme,),
                ).fetchall()
            else:
                rows = c.execute(
                    "SELECT course_code, course_name, programme, semester, credits FROM courses ORDER BY programme, semester, course_code"
                ).fetchall()
        return [CourseRow(**dict(r)) for r in rows]

    def upsert(self, row: CourseRow, conn: Optional[sqlite3.Connection] = None) -> None:
        sql = (
            "INSERT INTO courses(course_code, course_name, programme, semester, credits) VALUES (?,?,?,?,?) "
            "ON CONFLICT(course_code) DO UPDATE SET course_name=excluded.course_name, programme=excluded.programme, "
            "semester=excluded.semester, credits=excluded.credits"
        )
        args = (row.course_code.upper(), row.course_name, row.programme, row.semester, row.credits)
        if conn is not None:
            conn.execute(sql, args)
        else:
            with get_conn() as c:
                c.execute(sql, args)

    def count(self) -> int:
        with get_conn() as c:
            return int(c.execute("SELECT COUNT(*) FROM courses").fetchone()[0])


# --------------------------------------------------------------------------------------------
# Attendance & results (personal data: always scoped by student_id)
# --------------------------------------------------------------------------------------------
class AttendanceRepo:
    def get(self, student_id: str, course_code: str) -> Optional[AttendanceRow]:
        with get_conn() as c:
            row = c.execute(
                "SELECT student_id, course_code, classes_held, classes_attended FROM attendance "
                "WHERE student_id = ? AND course_code = ?",
                (student_id, course_code.upper()),
            ).fetchone()
        return AttendanceRow(**dict(row)) if row else None

    def list_for_student(self, student_id: str) -> list[AttendanceRow]:
        with get_conn() as c:
            rows = c.execute(
                "SELECT student_id, course_code, classes_held, classes_attended FROM attendance "
                "WHERE student_id = ? ORDER BY course_code",
                (student_id,),
            ).fetchall()
        return [AttendanceRow(**dict(r)) for r in rows]

    def upsert(self, row: AttendanceRow, conn: Optional[sqlite3.Connection] = None) -> None:
        sql = (
            "INSERT INTO attendance(student_id, course_code, classes_held, classes_attended) VALUES (?,?,?,?) "
            "ON CONFLICT(student_id, course_code) DO UPDATE SET classes_held=excluded.classes_held, "
            "classes_attended=excluded.classes_attended"
        )
        args = (row.student_id, row.course_code.upper(), row.classes_held, row.classes_attended)
        if conn is not None:
            conn.execute(sql, args)
        else:
            with get_conn() as c:
                c.execute(sql, args)


class ResultRepo:
    _COLS = "student_id, course_code, exam_session, exam_type, internal_marks, external_marks, total_marks, max_marks, result"

    def list_for_student(self, student_id: str, course_code: Optional[str] = None) -> list[ResultRow]:
        with get_conn() as c:
            if course_code:
                rows = c.execute(
                    f"SELECT {self._COLS} FROM results WHERE student_id = ? AND course_code = ? "
                    "ORDER BY exam_session, exam_type",
                    (student_id, course_code.upper()),
                ).fetchall()
            else:
                rows = c.execute(
                    f"SELECT {self._COLS} FROM results WHERE student_id = ? ORDER BY course_code, exam_session, exam_type",
                    (student_id,),
                ).fetchall()
        return [ResultRow(**dict(r)) for r in rows]

    def upsert(self, row: ResultRow, conn: Optional[sqlite3.Connection] = None) -> None:
        sql = (
            f"INSERT INTO results({self._COLS}) VALUES (?,?,?,?,?,?,?,?,?) "
            "ON CONFLICT(student_id, course_code, exam_session, exam_type) DO UPDATE SET "
            "internal_marks=excluded.internal_marks, external_marks=excluded.external_marks, "
            "total_marks=excluded.total_marks, max_marks=excluded.max_marks, result=excluded.result"
        )
        args = (
            row.student_id, row.course_code.upper(), row.exam_session, row.exam_type, row.internal_marks,
            row.external_marks, row.total_marks, row.max_marks, row.result,
        )
        if conn is not None:
            conn.execute(sql, args)
        else:
            with get_conn() as c:
                c.execute(sql, args)


# --------------------------------------------------------------------------------------------
# Rule registry (Annex C)
# --------------------------------------------------------------------------------------------
_RULE_COLS = (
    "rule_id, description, parameter, operator, value, scope_programmes, scope_batches, effective_from, "
    "effective_to, source_doc_id, source_section, unit, attributes, origin, quote, chunk_id, source_page"
)


def _rule_from_row(row: sqlite3.Row) -> RuleRow:
    d = dict(row)
    d["attributes"] = json.loads(d["attributes"]) if d.get("attributes") else None
    d["effective_to"] = d["effective_to"] or None
    return RuleRow(**d)


class RuleRepo:
    def candidates(self, parameter: str) -> list[RuleRow]:
        with get_conn() as c:
            rows = c.execute(
                f"SELECT {_RULE_COLS} FROM rule_registry WHERE parameter = ? ORDER BY effective_from, rule_id",
                (parameter,),
            ).fetchall()
        return [_rule_from_row(r) for r in rows]

    def get(self, rule_id: str) -> Optional[RuleRow]:
        with get_conn() as c:
            row = c.execute(f"SELECT {_RULE_COLS} FROM rule_registry WHERE rule_id = ?", (rule_id,)).fetchone()
        return _rule_from_row(row) if row else None

    def list_all(self) -> list[RuleRow]:
        with get_conn() as c:
            rows = c.execute(f"SELECT {_RULE_COLS} FROM rule_registry ORDER BY parameter, effective_from, rule_id").fetchall()
        return [_rule_from_row(r) for r in rows]

    def parameters(self) -> list[str]:
        with get_conn() as c:
            return [r[0] for r in c.execute("SELECT DISTINCT parameter FROM rule_registry ORDER BY parameter").fetchall()]

    def upsert(self, row: RuleRow, conn: Optional[sqlite3.Connection] = None) -> None:
        sql = (
            f"INSERT INTO rule_registry({_RULE_COLS}, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
            "ON CONFLICT(rule_id) DO UPDATE SET description=excluded.description, parameter=excluded.parameter, "
            "operator=excluded.operator, value=excluded.value, scope_programmes=excluded.scope_programmes, "
            "scope_batches=excluded.scope_batches, effective_from=excluded.effective_from, effective_to=excluded.effective_to, "
            "source_doc_id=excluded.source_doc_id, source_section=excluded.source_section, unit=excluded.unit, "
            "attributes=excluded.attributes, origin=excluded.origin, quote=excluded.quote, chunk_id=excluded.chunk_id, "
            "source_page=excluded.source_page"
        )
        args = (
            row.rule_id, row.description, row.parameter, row.operator, row.value, row.scope_programmes, row.scope_batches,
            row.effective_from, row.effective_to or None, row.source_doc_id, row.source_section, row.unit,
            json.dumps(row.attributes) if row.attributes else None, row.origin, row.quote, row.chunk_id,
            row.source_page, now_iso(),
        )
        if conn is not None:
            conn.execute(sql, args)
        else:
            with get_conn() as c:
                c.execute(sql, args)

    def delete_extracted_for_doc(self, doc_id: str, conn: Optional[sqlite3.Connection] = None) -> int:
        sql = "DELETE FROM rule_registry WHERE source_doc_id = ? AND origin = 'extracted'"
        if conn is not None:
            return conn.execute(sql, (doc_id,)).rowcount
        with get_conn() as c:
            return c.execute(sql, (doc_id,)).rowcount

    def for_doc(self, doc_id: str) -> list[RuleRow]:
        with get_conn() as c:
            rows = c.execute(
                f"SELECT {_RULE_COLS} FROM rule_registry WHERE source_doc_id = ? ORDER BY rule_id", (doc_id,)
            ).fetchall()
        return [_rule_from_row(r) for r in rows]

    def count(self) -> int:
        with get_conn() as c:
            return int(c.execute("SELECT COUNT(*) FROM rule_registry").fetchone()[0])


# --------------------------------------------------------------------------------------------
# Chunks (SQLite is the system of record for chunk text + metadata; Chroma holds the vectors)
# --------------------------------------------------------------------------------------------
_CHUNK_COLS = (
    "chunk_id, doc_id, ordinal, section_number, section_title, section_path, heading_level, page, kind, text, "
    "embed_text, table_json, references_json, prev_chunk_id, next_chunk_id, content_hash, injection_suspected, "
    "confidence, ocr"
)


def _chunk_from_row(row: sqlite3.Row) -> ChunkRow:
    d = dict(row)
    d["section_path"] = json.loads(d["section_path"] or "[]")
    d["table_json"] = json.loads(d["table_json"]) if d.get("table_json") else None
    d["references"] = json.loads(d.pop("references_json") or "[]")
    d["injection_suspected"] = bool(d["injection_suspected"])
    d["ocr"] = bool(d["ocr"])
    return ChunkRow(**d)


class ChunkRepo:
    def insert_many(self, chunks: Iterable[ChunkRow], conn: Optional[sqlite3.Connection] = None) -> int:
        sql = f"INSERT OR REPLACE INTO chunks({_CHUNK_COLS}) VALUES ({','.join('?' * 19)})"
        data = [
            (
                ch.chunk_id, ch.doc_id, ch.ordinal, ch.section_number, ch.section_title, json.dumps(ch.section_path),
                ch.heading_level, ch.page, ch.kind, ch.text, ch.embed_text,
                json.dumps(ch.table_json) if ch.table_json else None, json.dumps(ch.references), ch.prev_chunk_id,
                ch.next_chunk_id, ch.content_hash, int(ch.injection_suspected), ch.confidence, int(ch.ocr),
            )
            for ch in chunks
        ]
        if conn is not None:
            conn.executemany(sql, data)
        else:
            with get_conn() as c:
                c.executemany(sql, data)
        return len(data)

    def delete_by_doc(self, doc_id: str, conn: Optional[sqlite3.Connection] = None) -> int:
        sql = "DELETE FROM chunks WHERE doc_id = ?"
        if conn is not None:
            return conn.execute(sql, (doc_id,)).rowcount
        with get_conn() as c:
            return c.execute(sql, (doc_id,)).rowcount

    def get(self, chunk_id: str) -> Optional[ChunkRow]:
        with get_conn() as c:
            row = c.execute(f"SELECT {_CHUNK_COLS} FROM chunks WHERE chunk_id = ?", (chunk_id,)).fetchone()
        return _chunk_from_row(row) if row else None

    def get_many(self, chunk_ids: list[str]) -> dict[str, ChunkRow]:
        if not chunk_ids:
            return {}
        out: dict[str, ChunkRow] = {}
        with get_conn() as c:
            for i in range(0, len(chunk_ids), 500):
                batch = chunk_ids[i : i + 500]
                marks = ",".join("?" * len(batch))
                rows = c.execute(f"SELECT {_CHUNK_COLS} FROM chunks WHERE chunk_id IN ({marks})", batch).fetchall()
                for r in rows:
                    ch = _chunk_from_row(r)
                    out[ch.chunk_id] = ch
        return out

    def by_doc(self, doc_id: str) -> list[ChunkRow]:
        with get_conn() as c:
            rows = c.execute(f"SELECT {_CHUNK_COLS} FROM chunks WHERE doc_id = ? ORDER BY ordinal", (doc_id,)).fetchall()
        return [_chunk_from_row(r) for r in rows]

    def all(self) -> list[ChunkRow]:
        with get_conn() as c:
            rows = c.execute(f"SELECT {_CHUNK_COLS} FROM chunks ORDER BY doc_id, ordinal").fetchall()
        return [_chunk_from_row(r) for r in rows]

    def find_by_section(self, doc_id: str, section_number: str) -> list[ChunkRow]:
        """Chunks whose section number equals, or is nested under, the given clause number."""
        like = section_number.replace("%", "").replace("_", "") + ".%"
        with get_conn() as c:
            rows = c.execute(
                f"SELECT {_CHUNK_COLS} FROM chunks WHERE doc_id = ? AND (section_number = ? OR section_number LIKE ?) "
                "ORDER BY ordinal",
                (doc_id, section_number, like),
            ).fetchall()
        return [_chunk_from_row(r) for r in rows]

    def count(self) -> int:
        with get_conn() as c:
            return int(c.execute("SELECT COUNT(*) FROM chunks").fetchone()[0])


# --------------------------------------------------------------------------------------------
# Audit
# --------------------------------------------------------------------------------------------
class AuditRepo:
    def insert(self, trace_id: str, ts: str, student_id_hash: Optional[str], question_hash: str,
               category: Optional[str], answer_type: Optional[str], latency_ms: int, record: dict) -> None:
        with get_conn() as c:
            c.execute(
                "INSERT OR REPLACE INTO audit_log(trace_id, ts, student_id_hash, question_hash, question_category, "
                "answer_type, latency_ms, record_json) VALUES (?,?,?,?,?,?,?,?)",
                (trace_id, ts, student_id_hash, question_hash, category, answer_type, latency_ms,
                 json.dumps(record, default=str, ensure_ascii=False)),
            )

    def get(self, trace_id: str) -> Optional[dict]:
        with get_conn() as c:
            row = c.execute("SELECT record_json FROM audit_log WHERE trace_id = ?", (trace_id,)).fetchone()
        return json.loads(row["record_json"]) if row else None

    def count(self) -> int:
        with get_conn() as c:
            return int(c.execute("SELECT COUNT(*) FROM audit_log").fetchone()[0])


# --------------------------------------------------------------------------------------------
# Embedding cache
# --------------------------------------------------------------------------------------------
class EmbeddingCacheRepo:
    def get_many(self, model: str, hashes: list[str]) -> dict[str, bytes]:
        if not hashes:
            return {}
        out: dict[str, bytes] = {}
        with get_conn() as c:
            for i in range(0, len(hashes), 500):
                batch = hashes[i : i + 500]
                marks = ",".join("?" * len(batch))
                rows = c.execute(
                    f"SELECT text_hash, vector FROM embedding_cache WHERE model = ? AND text_hash IN ({marks})",
                    [model, *batch],
                ).fetchall()
                for r in rows:
                    out[r["text_hash"]] = bytes(r["vector"])
        return out

    def put_many(self, model: str, items: dict[str, bytes]) -> None:
        if not items:
            return
        with get_conn() as c:
            c.executemany(
                "INSERT OR REPLACE INTO embedding_cache(model, text_hash, vector) VALUES (?,?,?)",
                [(model, h, v) for h, v in items.items()],
            )
