"""Synthetic university: "Meridian Institute of Technology" (fictional).

Everything here is template text written for this project, not generated by a model and not copied from a real institution.
Each document is marked synthetic=Y in the Source Register. Replace these files (and keep the same metadata columns) with real
university documents when they are available: nothing else in the system depends on this content.

The corpus is built to exercise the policy, not to be realistic prose:
  * ACAD-REG-2024 (level 1) says 75% attendance; ACAD-2026-08 (level 2) supersedes clause 7.2 with 80% for B.Tech programmes.
  * DEPT-FAQ-CSE (level 4, newer) says 65%: a lower authority that must lose even though it is the newest document.
  * PLACEMENT-2027 (level 2) is not yet in force on 2026-10-06 and raises the placement CGPA from 6.5 to 7.0.
  * SCH-NOTICE-A / SCH-NOTICE-B (both level 3, same date) disagree on the scholarship deadline: unresolvable, must be flagged.
  * STUDENT-FORUM-NOTES (level 5) is unofficial and must never override anything.
  * LIBRARY-RULES is an image-only scanned PDF (OCR path); SUP-NOTICE-2026 and ACAD-2026-08 are DOCX; DEPT-FAQ-CSE is Markdown.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

INSTITUTE = "Meridian Institute of Technology"


@dataclass
class Section:
    number: str
    title: str
    paragraphs: list[str] = field(default_factory=list)
    table: Optional[list[list[str]]] = None
    table_caption: str = ""


@dataclass
class DocSpec:
    doc_id: str
    title: str
    issuer: str
    authority_level: int
    doc_type: str
    version: str
    effective_from: str
    fmt: str  # pdf | docx | md | scanned
    sections: list[Section]
    effective_to: str = ""
    supersedes: str = ""
    scope_programmes: str = "ALL"
    scope_batches: str = "ALL"
    provenance: str = "Synthetic document written for this project (template text, no real institution)"
    intro: str = ""

    @property
    def filename(self) -> str:
        return f"{self.doc_id}.{ {'pdf': 'pdf', 'docx': 'docx', 'md': 'md', 'scanned': 'pdf'}[self.fmt] }"


GRADE_TABLE = [["Marks (%)", "Grade", "Grade points"], ["90-100", "O", "10"], ["80-89", "A", "9"], ["70-79", "B", "8"], ["60-69", "C", "7"],
               ["50-59", "D", "6"], ["40-49", "E", "5"], ["Below 40", "F", "0"]]

DOCS: list[DocSpec] = [
    DocSpec(
        doc_id="ACAD-REG-2024", title="Academic Regulations 2024", issuer="Academic Senate, Meridian Institute of Technology",
        authority_level=1, doc_type="regulation", version="3.1", effective_from="2024-07-01", fmt="pdf", scope_batches="2022+",
        intro="These regulations govern examinations, attendance, supplementary examinations, placements and scholarships.",
        sections=[
            Section("1", "General", ["1.1 These regulations apply to all students admitted from the 2022 batch onwards."]),
            Section("5", "Examinations and Grading", [
                "5.1 A student must secure a minimum of 40% of the total marks in a course to pass the course.",
                "5.2 Grade points are awarded on the scale in the table below and CGPA is the credit-weighted average of grade points."],
                table=GRADE_TABLE, table_caption="Grade scale"),
            Section("6", "Supplementary Examinations", [
                "6.1 A student whose result in the regular examination is FAIL or ABSENT may appear in the supplementary examination for that course.",
                "6.2 A student is allowed a maximum of 3 attempts in a course, counting the regular examination and all supplementary examinations.",
                "6.3 A student must satisfy the attendance requirement in clause 7.2 to appear in a supplementary examination."]),
            Section("7", "Attendance", [
                "7.1 Attendance in a course is the number of classes attended divided by the number of classes held, expressed as a percentage.",
                "7.2 A student shall have a minimum of 75% attendance in each course to appear in the end-semester examination.",
                "7.3 Attendance in laboratory courses is computed in the same way as in theory courses.",
                "7.4 Attendance between 65% and 75% may be condoned by the Dean (Academics) on payment of the prescribed fee, subject to clause 7.2.",
                "7.5 A student with attendance below 65% shall be detained in that course."]),
            Section("11", "Placements", [
                "11.1 To sit for campus placements a student must have a minimum CGPA of 6.5.",
                "11.2 A student may have no more than 1 active backlog at the time of placement registration."]),
            Section("12", "Scholarships", [
                "12.1 The merit scholarship requires a minimum CGPA of 8.0 in the preceding semesters."]),
        ]),
    DocSpec(
        doc_id="ACAD-2026-08", title="Circular on Revised Minimum Attendance", issuer="Office of the Dean (Academics)",
        authority_level=2, doc_type="circular", version="1.0", effective_from="2026-08-01", fmt="docx",
        supersedes="ACAD-REG-2024#7.2", scope_programmes="B.Tech CSE;B.Tech ECE",
        intro="Circular issued by the Dean (Academics) with the approval of the Academic Senate.",
        sections=[
            Section("1", "Purpose", ["1.1 This circular revises the minimum attendance requirement for B.Tech programmes."]),
            Section("2", "Revised attendance requirement", [
                "2.1 With effect from 1 August 2026 a student of a B.Tech programme shall have a minimum of 80% attendance in each course to appear in the end-semester examination.",
                "2.2 Clause 7.2 of the Academic Regulations 2024 stands superseded for B.Tech programmes."]),
            Section("3", "Condonation", ["3.1 The provisions of clause 7.4 of the Academic Regulations 2024 continue to apply."]),
        ]),
    DocSpec(
        doc_id="PLACEMENT-2027", title="Circular on Placement Eligibility 2027", issuer="Office of the Dean (Academics)",
        authority_level=2, doc_type="circular", version="1.0", effective_from="2027-01-01", fmt="docx",
        supersedes="ACAD-REG-2024#11.1", scope_programmes="B.Tech CSE",
        sections=[Section("1", "Revised placement CGPA", [
            "1.1 With effect from 1 January 2027 a minimum CGPA of 7.0 is required to sit for campus placements by students of B.Tech CSE."])]),
    DocSpec(
        doc_id="SUP-NOTICE-2026", title="Supplementary Examination Notice 2026", issuer="Controller of Examinations",
        authority_level=2, doc_type="notice", version="1.0", effective_from="2026-09-01", effective_to="2027-03-31", fmt="docx",
        sections=[
            Section("1", "Eligibility", ["1.1 A student whose latest result in a course is FAIL or ABSENT may apply for the supplementary examination in that course."]),
            Section("2", "Last date and fee", [
                "2.1 The last date to apply for the supplementary examination is 15 November 2026.",
                "2.2 The supplementary examination fee is Rs. 2,500 per course."]),
            Section("3", "How to apply", [
                "3.1 Log in to the examination portal.", "3.2 Select the course and pay the supplementary examination fee.", "3.3 Download the hall ticket after the fee is confirmed."]),
        ]),
    DocSpec(
        doc_id="DEPT-FAQ-CSE", title="Department of CSE Student FAQ", issuer="Department of Computer Science and Engineering",
        authority_level=4, doc_type="faq", version="2.0", effective_from="2026-09-15", fmt="md", scope_programmes="B.Tech CSE",
        sections=[
            Section("1", "Academic advisor", ["1.1 Every student is assigned an academic advisor in the first week of the semester."]),
            Section("3", "Minimum attendance", ["3.1 Students need a minimum of 65% attendance to sit for the end-semester examination."]),
            Section("4", "Lab timings", ["4.1 Laboratories are open from 9:00 to 17:00 on working days."]),
        ]),
    DocSpec(
        doc_id="HOSTEL-HANDBOOK", title="Hostel Handbook 2025-26", issuer="Office of the Chief Warden", authority_level=4, doc_type="handbook",
        version="1.2", effective_from="2025-07-01", fmt="pdf",
        sections=[
            Section("1", "Curfew", ["1.1 Residents must return to the hostel by 22:00 on weekdays and by 23:30 on weekends."]),
            Section("2", "Visitors", ["2.1 Visitors are permitted only between 10:00 and 18:00 in the visitor lounge."]),
            Section("3", "Fees", ["3.1 Hostel fees are payable once per semester as set out below."],
                    table=[["Item", "Amount"], ["Security deposit", "Rs. 10,000"], ["Mess fee per month", "Rs. 4,500"], ["Room rent per semester", "Rs. 30,000"]],
                    table_caption="Hostel fees"),
            Section("4", "Mess timings", ["4.1 Breakfast is served from 7:30 to 9:00, lunch from 12:30 to 14:00 and dinner from 19:30 to 21:00."]),
        ]),
    DocSpec(
        doc_id="LIBRARY-RULES", title="Central Library Rules", issuer="Central Library", authority_level=4, doc_type="handbook", version="1.0",
        effective_from="2025-07-01", fmt="scanned",
        sections=[
            Section("1", "Borrowing", ["1.1 A student may borrow up to 4 books at a time for 14 days.", "1.2 A late fee of Rs. 5 per day is charged for each overdue book."]),
        ]),
    DocSpec(
        doc_id="SCH-NOTICE-A", title="Merit Scholarship Application Notice (Scholarship Cell)", issuer="Scholarship Cell", authority_level=3,
        doc_type="notice", version="1.0", effective_from="2026-09-01", fmt="md",
        sections=[Section("1", "Application deadline", ["1.1 The last date to apply for the merit scholarship is 2026-11-10."])]),
    DocSpec(
        doc_id="SCH-NOTICE-B", title="Merit Scholarship Application Notice (Dean of Students)", issuer="Dean of Students", authority_level=3,
        doc_type="notice", version="1.0", effective_from="2026-09-01", fmt="md",
        sections=[Section("1", "Application deadline", ["1.1 The last date to apply for the merit scholarship is 2026-11-20."])]),
    DocSpec(
        doc_id="STUDENT-FORUM-NOTES", title="Student Forum Notes (unofficial)", issuer="Student forum volunteers", authority_level=5,
        doc_type="unofficial", version="0.1", effective_from="2026-09-20", fmt="md",
        provenance="Synthetic document: stands in for untrusted community content",
        sections=[Section("1", "Attendance tips", ["1.1 Seniors say a minimum of 60% attendance is enough to sit for the end-semester examination."])]),
]

# Curated rule_registry rows (Annex C). Each points at a clause that exists in the document above.
# Format: rule_id, parameter, operator, value, unit, doc_id, section, effective_from, effective_to, scope_programmes, scope_batches
GOLD_RULES: list[dict[str, str]] = [
    dict(rule_id="ATT-MIN-01", parameter="min_attendance_pct", operator=">=", value="75", unit="pct", source_doc_id="ACAD-REG-2024", source_section="7.2",
         effective_from="2024-07-01", description="Minimum 75% attendance per course to appear in the end-semester examination"),
    dict(rule_id="ATT-MIN-02", parameter="min_attendance_pct", operator=">=", value="80", unit="pct", source_doc_id="ACAD-2026-08", source_section="2.1",
         effective_from="2026-08-01", scope_programmes="B.Tech CSE;B.Tech ECE", description="Minimum 80% attendance for B.Tech programmes (supersedes clause 7.2 of ACAD-REG-2024)"),
    dict(rule_id="ATT-MIN-FAQ", parameter="min_attendance_pct", operator=">=", value="65", unit="pct", source_doc_id="DEPT-FAQ-CSE", source_section="3.1",
         effective_from="2026-09-15", scope_programmes="B.Tech CSE", description="FAQ statement of 65% attendance (level 4, outranked)"),
    dict(rule_id="ATT-CON-01", parameter="condonation_min_attendance_pct", operator=">=", value="65", unit="pct", source_doc_id="ACAD-REG-2024", source_section="7.4",
         effective_from="2024-07-01", description="Attendance between 65% and 75% may be condoned"),
    dict(rule_id="PASS-MIN-01", parameter="pass_marks_pct", operator=">=", value="40", unit="pct", source_doc_id="ACAD-REG-2024", source_section="5.1",
         effective_from="2024-07-01", description="Minimum 40% of total marks to pass a course"),
    dict(rule_id="SUP-RES-01", parameter="sup_eligible_results", operator="in", value="FAIL;ABSENT", unit="", source_doc_id="ACAD-REG-2024", source_section="6.1",
         effective_from="2024-07-01", description="Results that allow a supplementary attempt"),
    dict(rule_id="SUP-ATT-01", parameter="sup_max_attempts", operator="<=", value="3", unit="count", source_doc_id="ACAD-REG-2024", source_section="6.2",
         effective_from="2024-07-01", description="Maximum 3 attempts per course"),
    dict(rule_id="SUP-DL-01", parameter="sup_application_deadline", operator="<=", value="2026-11-15", unit="date", source_doc_id="SUP-NOTICE-2026", source_section="2.1",
         effective_from="2026-09-01", effective_to="2027-03-31", description="Last date to apply for the supplementary examination"),
    dict(rule_id="SUP-FEE-01", parameter="sup_exam_fee", operator="==", value="2500", unit="currency", source_doc_id="SUP-NOTICE-2026", source_section="2.2",
         effective_from="2026-09-01", effective_to="2027-03-31", description="Supplementary examination fee per course (INR)"),
    dict(rule_id="PLC-CGPA-01", parameter="placement_min_cgpa", operator=">=", value="6.5", unit="cgpa", source_doc_id="ACAD-REG-2024", source_section="11.1",
         effective_from="2024-07-01", description="Minimum CGPA 6.5 to sit for campus placements"),
    dict(rule_id="PLC-CGPA-02", parameter="placement_min_cgpa", operator=">=", value="7.0", unit="cgpa", source_doc_id="PLACEMENT-2027", source_section="1.1",
         effective_from="2027-01-01", scope_programmes="B.Tech CSE", description="Minimum CGPA 7.0 for B.Tech CSE from 2027-01-01"),
    dict(rule_id="PLC-BKL-01", parameter="placement_max_active_backlogs", operator="<=", value="1", unit="count", source_doc_id="ACAD-REG-2024", source_section="11.2",
         effective_from="2024-07-01", description="At most 1 active backlog at placement registration"),
    dict(rule_id="SCH-CGPA-01", parameter="scholarship_min_cgpa", operator=">=", value="8.0", unit="cgpa", source_doc_id="ACAD-REG-2024", source_section="12.1",
         effective_from="2024-07-01", description="Minimum CGPA 8.0 for the merit scholarship"),
    dict(rule_id="SCH-DL-01", parameter="scholarship_application_deadline", operator="<=", value="2026-11-10", unit="date", source_doc_id="SCH-NOTICE-A", source_section="1.1",
         effective_from="2026-09-01", description="Scholarship deadline per the Scholarship Cell"),
    dict(rule_id="SCH-DL-02", parameter="scholarship_application_deadline", operator="<=", value="2026-11-20", unit="date", source_doc_id="SCH-NOTICE-B", source_section="1.1",
         effective_from="2026-09-01", description="Scholarship deadline per the Dean of Students"),
    dict(rule_id="ATT-MIN-FORUM", parameter="min_attendance_pct", operator=">=", value="60", unit="pct", source_doc_id="STUDENT-FORUM-NOTES", source_section="1.1",
         effective_from="2026-09-20", description="Unofficial forum claim of 60% (level 5, informational only)"),
]
